name: submit

services:
  db:
    image: postgres:12.4
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: localdevuser
      POSTGRES_PASSWORD: localdevuser
      POSTGRES_DB: moresleeplocal

  moresleep:
    image: ghcr.io/javabin/moresleep:edge
    ports:
      - "8082:8082"
    env_file:
      - path: ./.env.moresleep
        required: false
    environment:
      DBHOST: db
    links:
      - db

  submit:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    env_file:
      - path: ./.env
        required: false
    environment:
      - TALKS_LOCATION=${TALKS_LOCATION:-http://moresleep:8082}
    links:
      - moresleep