name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
        cache: maven

    - name: Build
      run: make build

  docker:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
        cache: maven

    - name: Build
      run: make build

    - name: Build and push [edge]
      run: docker buildx build --push -t ghcr.io/javabin/submittheforce:edge -f src/main/docker/Dockerfile.jvm --platforms linux/amd64,linux/arm64 .

    - name: Build and push [latest]
      if: startsWith(github.ref, 'refs/tags/v')
      run: docker buildx build --push -t ghcr.io/javabin/submittheforce:latest -f src/main/docker/Dockerfile.jvm --platforms linux/amd64,linux/arm64 .

  uber-jar:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
        cache: maven

    - name: Build uber-JAR
      run: make build build-uber

    - name: Upload asset
      uses: k15g/action-github-asset-upload@edge
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: target/submit-runner.jar
        name: submit-runner.jar
        type: application/java-archive
        label: Uber-JAR
